services:
  flask:
    build: .
    ports:
      - 8088:8088
    environment:
      PORT: 8088
      DB_CONNECTION_STRING: featuretoggle.rzbemle.mongodb.net
      DB_NAME: FeatureToggle
      DB_USERNAME: tomc
      DB_PASSWORD: ZV7nQrEkOHfY6XtC
    depends_on:
      - mongo
      
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: tomc
      MONGO_INITDB_ROOT_PASSWORD: ZV7nQrEkOHfY6XtC
